language: c++
sudo: required
services:
    - docker
before_install:
    - .github/runchecks
    - docker pull opensuse
    - docker run -it -d -h testdev.pbspro.com --name testdev -v `pwd`:`pwd` --privileged -w `pwd` opensuse /bin/sh
    - docker ps -a
    - export DOCKER_EXEC_TTY="docker exec -it testdev"
    - export DOCKER_EXEC="docker exec -i testdev"
    - export DOCKER_TESTDEV_IP="$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' testdev)"
    - ${DOCKER_EXEC} /bin/sh -c "echo '${DOCKER_TESTDEV_IP}     testdev' >> /etc/hosts"
    - ${DOCKER_EXEC} cat /etc/hosts
install:
    - export OS_NAME=$(${DOCKER_EXEC} cat /etc/os-release | awk -F[=\"] '/^NAME=/ {print $3}')
    - export OS_VERSION=$(${DOCKER_EXEC} cat /etc/os-release | awk -F[=\"] '/VERSION=/ {print $3}')
    - export OS_NAME_VERSION=${OS_NAME// /_}_${OS_VERSION// /_}
    - ${DOCKER_EXEC} zypper -n ar -f -G http://download.opensuse.org/repositories/devel:/tools/${OS_NAME_VERSION}/devel:tools.repo
    - ${DOCKER_EXEC} zypper -n install time.x86_64
    - ${DOCKER_EXEC} zypper -n ref
    - ${DOCKER_EXEC} zypper -n install rpmdevtools
    - ${DOCKER_EXEC} rpmdev-setuptree
    - ${DOCKER_EXEC} zypper -n install git 
    - ${DOCKER_EXEC_TTY} git clone https://github.com/PBSPro/pbspro.git 
    - ${DOCKER_EXEC} /bin/ls
    - ${DOCKER_EXEC} /bin/cd pbspro
    - ${DOCKER_EXEC} /bin/sh -c "zypper -n install \$(rpmspec --buildrequires -q pbspro.spec)"
    - ${DOCKER_EXEC} ./autogen.sh
    - ${DOCKER_EXEC} ./configure
    - ${DOCKER_EXEC} ./make dist
    - ${DOCKER_EXEC} /bin/sh -c 'cp -fv pbspro-*.tar.gz /root/rpmbuild/SOURCES/'
    - ${DOCKER_EXEC} rpmbuild -bb pbspro.spec
    - ${DOCKER_EXEC} /bin/sh -c 'zypper -n install /root/rpmbuild/RPMS/x86_64/pbspro-server-*.x86_64.rpm'
    - ${DOCKER_EXEC} /bin/cd ..
    - ${DOCKER_EXEC} /etc/init.d/pbs start
script: true
